// <auto-generated />
using System;
using ApiCursoEntityFrameworkCore.ApplicationDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace ApiCursoEntityFrameworkCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241227185103_FilmsMovieTheaterAndConventionToDate")]
    partial class FilmsMovieTheaterAndConventionToDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biografy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ActorTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GenreId")
                        .HasColumnType("integer");

                    b.Property<bool>("InMovie")
                        .HasColumnType("boolean");

                    b.Property<string>("Poster")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("PremiereDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("FilmTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.FilmsActors", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("Character")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("FilmsActorsTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.FilmsGenres", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("FilmsGenreTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.FilmsMovieTheaters", b =>
                {
                    b.Property<int>("FilmId")
                        .HasColumnType("integer");

                    b.Property<int>("MovieTheaterId")
                        .HasColumnType("integer");

                    b.HasKey("FilmId", "MovieTheaterId");

                    b.HasIndex("MovieTheaterId");

                    b.ToTable("FilmsMovieTheaterTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("GenreTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<NpgsqlPoint>("Location")
                        .HasColumnType("point");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("MovieTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.MovieTheater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)");

                    b.Property<int>("TypeMovieTheater")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieTheaterTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.OfferMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("MovieId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PercentageDiscount")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("OfferMovieTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PeopleTable");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Film", b =>
                {
                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Genre", null)
                        .WithMany("Films")
                        .HasForeignKey("GenreId");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.FilmsActors", b =>
                {
                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Actor", "Actor")
                        .WithMany("FilmsActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Film", "Film")
                        .WithMany("FilmsActors")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Film");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.FilmsGenres", b =>
                {
                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Film", "Film")
                        .WithMany("FilmsGenres")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Genre", "Genre")
                        .WithMany("FilmsGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.FilmsMovieTheaters", b =>
                {
                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Film", "Film")
                        .WithMany("FilmsMovieTheaters")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.MovieTheater", "MovieTheater")
                        .WithMany("FilmsMovieTheaters")
                        .HasForeignKey("MovieTheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");

                    b.Navigation("MovieTheater");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.MovieTheater", b =>
                {
                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Movie", "Movie")
                        .WithMany("MovieTheaters")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.OfferMovie", b =>
                {
                    b.HasOne("ApiCursoEntityFrameworkCore.Entities.Movie", null)
                        .WithOne("OfferMovie")
                        .HasForeignKey("ApiCursoEntityFrameworkCore.Entities.OfferMovie", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Actor", b =>
                {
                    b.Navigation("FilmsActors");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Film", b =>
                {
                    b.Navigation("FilmsActors");

                    b.Navigation("FilmsGenres");

                    b.Navigation("FilmsMovieTheaters");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Genre", b =>
                {
                    b.Navigation("Films");

                    b.Navigation("FilmsGenres");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.Movie", b =>
                {
                    b.Navigation("MovieTheaters");

                    b.Navigation("OfferMovie");
                });

            modelBuilder.Entity("ApiCursoEntityFrameworkCore.Entities.MovieTheater", b =>
                {
                    b.Navigation("FilmsMovieTheaters");
                });
#pragma warning restore 612, 618
        }
    }
}
